lddt_main_homepage:
    path:     /
    defaults: { _controller: LddtMainBundle:Default:index }

lddt_main_test:
    path:     /test
    defaults: { _controller: LddtMainBundle:Default:test}

lddt_main_create:
    path:     /create
    defaults: { _controller: LddtMainBundle:Default:create }

lddt_main_show:
    path:     /dessin/{id}
    defaults: { _controller: LddtMainBundle:Default:show }
    requirements:
      id: \d+

lddt_main_edit:
    path:     /edit/{id}
    defaults: { _controller: LddtMainBundle:Default:edit }
    requirements:
      id: \d+

lddt_main_delete:
    path:     /delete/{id}
    defaults: { _controller: LddtMainBundle:Default:delete }
    requirements:
      id: \d+

lddt_main_draws_by_cat:
    path:    /category/{id}
    defaults: { _controller: LddtMainBundle:Default:listDrawsByCat}
    requirements:
       id: \d+

lddt_main_draws_by_author:
    path:    /author/{id}
    defaults: { _controller: LddtMainBundle:Default:listDrawsByAuthor}
    requirements:
       id: \d+

lddt_main_draws_publish:
    path:    /dessin/publish/{id}
    defaults: { _controller: LddtMainBundle:Default:publishDraw}
    requirements:
       id: \d+

lddt_main_draws_by_color:
    path:    /color/{id}
    defaults: { _controller: LddtMainBundle:Default:listDrawsByColor}
    requirements:
       id: \d+